name: "Comment flake.lock changelog"
description: "Comment with changelogs on PRs that update flake.lock files."
branding:
  color: green
  icon: message-square
inputs:
  pull-request-number:
    description: "The number of the pull request to analyse"
    required: true
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    required: false
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.mjs
