name: ✅ Lint & test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: mdarocha/nix-magic-setup@1921e811898d32305cfbf959a6b9d6adf520df41 # unreleased: nix-magic-setup#25

      - run: devenv test
