name: ✅ Lint & test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: mdarocha/nix-magic-setup@815fe72057b1c901e5f6d987828d9a9ad0320df1 # main

      - run: devenv test
