name: ✅ Lint & test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: mdarocha/nix-magic-setup@e36d43dfbb22e406645941eb20ab8b8e276f0ebc # v1.4.0

      - run: devenv test
